### ISSUE TITLE
Implementar Suporte ao Protocolo ECDHE

### ISSUE THREAD

**Issue by rafaelsilvabr** [rafaelsilvabr/midlewareIoTSecurity#4]
**Tarefa:** Implementar suporte ao protocolo de criptografia ECDHE para dispositivos IoT.

**Descrição:** Esta tarefa envolve a configuração e implementação do protocolo ECDHE para dispositivos IoT, garantindo que a comunicação seja segura e eficiente, especialmente em dispositivos com recursos limitados.

**Comment by AugustoCesar20** [comment]
Para o encrypt usei o Camellia (para diferenciar o AES), na parte do descript eu manti o AES pq tava com alguns problemas no padding com o Camellia e as chaves gerei e deixei no aquivo json keys de forma estatica, o ideal seria gera-las a cada interação

**Comment by AugustoCesar20** [comment]
Para o encrypt usei o Camellia (para diferenciar o AES), na parte do descript eu manti o AES pq tava com alguns problemas no padding com o Camellia e as chaves gerei e deixei no aquivo json keys de forma estatica, o ideal seria gera-las a cada interação
